### ISSUE TITLE
Empty .obj file for OpenGate Type A

### ISSUE THREAD

**Issue by lululock71** [Robin-DUBREUIL/opengate#2]
Hi,

Wanted to work on a case for the Type A board but the .obj file of the PCBA seems to be invalid.

When attempting to create a shape from the mesh in FreeCAD, I get this error :

![Screenshot_20230507_174021](https://user-images.githubusercontent.com/58026350/236687791-e725422b-3702-451a-a77e-0b18e434db7e.png)

The 3D model doesn't seem to contain a shape (tested with FreeCAD and F3D), the viewport seems to be empty. Gonna try to open it with GLC Player as soon as my crappy laptop finishes compiling it.

![Screenshot_20230507_174622](https://user-images.githubusercontent.com/58026350/236688007-3e0ad8d4-08e3-46d2-89ea-e6f9f5624d42.png)

![Screenshot_20230507_174655](https://user-images.githubusercontent.com/58026350/236688060-68958d51-1cd0-4794-a414-f955ef64ca74.png)

Can you get a fixed 3D model, please ?

EDIT : MeshLab can't open it "No vertex found"
![Screenshot_20230507_180444](https://user-images.githubusercontent.com/58026350/236688950-7d618523-f5c3-46a6-a7db-536d3c711edb.png)

**Comment by lululock71** [comment]
Looks like the file I downloaded was corrupted somehow...

But the mesh still has issues. But I think it is fixable.

![Screenshot_20230507_181426](https://user-images.githubusercontent.com/58026350/236689463-f56dde08-f5e2-435d-b8d7-0112702b73e5.png)

**Comment by robindubreuil** [comment]
The file isn't perfect anyway, it is just a quick export on my PCB design software. For example, the thickness of the PCB is 1.6mm in this file even if functional models needs a 1.0mm thick PCB, this is due to limitations on the design software i use. The best would be to design a proper 3D model on an appropriate software, but the current design is too subject to changes to justify such a work, this is why i will close this issue for now.
Thanks for involving yourself in this project, and happy hacking!
